# -*- coding: utf-8 -*-
"""Tokyo-covid19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_9TKqhxovKCUEyiNbsvEQ-x3Co0A5kR
"""

from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import matplotlib
from matplotlib import  pyplot as plt

from urllib import request

re = request.urlopen('https://stopcovid19.metro.tokyo.lg.jp/')

content = re.read()

bs = BeautifulSoup(content)

data = {'陽性患者数 (日別)':[],
'検査実施人数 (日別)':[]}

for table in bs.find_all('table'):
    for th in table.thead.tr:
        if th['aria-label'] in data:
            date = []
            stat = []
            for tr in table.tbody:
                date.append(tr.th.get_text())
                stat.append(int(tr.td.get_text()))
            data[th['aria-label']] = [date,stat]

pos_data = data['陽性患者数 (日別)']
test_data = data['検査実施人数 (日別)']

date_convert = np.vectorize(lambda x: '2020/{}'.format(x))

def process(data):
    date, stats = data
    date = date_convert(date)
    t = matplotlib.dates.date2num(pd.to_datetime(date))
    return t, np.array(stats,dtype=np.int)

def plot(test, t1, pos, t2):
    start_idx = len(t2) - len(t1) - 1
    fig, ax = plt.subplots()
    fig.set_size_inches(18.5, 10.5)
    ax.bar(t1, test)
    ax.bar(t1, pos[start_idx:-1], color='r')
    ax.xaxis_date()
    ax2 = ax.twinx()
    postive_ratio = pos[start_idx:-1] * 100 / (test+0.0001)
    postive_ratio = np.clip(postive_ratio,0, 100)
    ax2.plot_date(t1, postive_ratio,fmt='o-',color='black')

t1, test = process(test_data)
t2, pos = process(pos_data)

plot(test,t1,pos,t2)

# 7 days moving average to remove 
moving_average = lambda x: np.convolve(x, np.ones((7,))/7, mode='valid')

plot(moving_average(test), t1[:-6], moving_average(pos), t2[:-6])



